service: product-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-openapi-documentation

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  documentation:
    version: '1'
    title: 'Product service API'
    description: 'Product service API documentation'
    models:
      - name: "GetProductsListResponse"
        description: "Get all products response"
        contentType: "application/json"
        schema: GetProductsListSchema
      - name: "GetProductByIdResponse"
        description: "Get product by id response"
        contentType: "application/json"
        schema: GetProductByIdSchema
      - name: "ErrorResponse"
        description: "An error response"
        contentType: "application/json"
        schema: ErrorResponseSchema
  serverless-offline:
    httpPort: 3001


functions:
  getProductsList:
    handler: src/handlers/getProductsList.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: src/handlers/getProductsById.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
